services:
  - type: web
    name: spring-boot-app
    env: java
    plan: free
    buildCommand: "./mvnw -f login-Bank-app/pom.xml clean package -DskipTests"
    startCommand: "java -jar login-Bank-app/target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
